'use strict';

module.exports = {
    DOCUMENT_STORE_API_ENDPOINT_DOCUMENTS: '',
    DOCUMENT_STORE_API_ENDPOINT_TRANSFERS: '',
    DOCUMENT_STORE_API_ENDPOINT_SOCKET_IO: '',
    APP_CREDENTIAL_USER: '',
    APP_CREDENTIAL_PASSWORD: '',
    FROM_DESTINATION: '',
    TO_DESTINATION: ''
}
